name: cgpa_calculator
description: A formal academic GPA calculator.
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Icons & Fonts
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  
  # Data Persistence
  shared_preferences: ^2.3.2
  
  # Charts
  fl_chart: ^0.66.2
  
  # PDF Generation
  pdf: ^3.11.1
  printing: ^5.13.2
  universal_html: ^2.2.4
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true